import { ModelType } from "src/modules/models/dto/model.dto";

export const TAVILY_BASE_URL = "https://api.tavily.com/";

export enum TextModelTier {
  ONE = "1",
  TWO = "2",
  THREE = "3",
}

export interface Model {
  id: number;
  name: string;
  displayName: string;
  description: string;
  modelType: ModelType;
  labels: string[];
  isProModel: boolean;
  isLoginRequired: boolean;
  capabilities?: string[];
  categories: string[];
  tier?: number;
}

export const AVAILABLE_MODELS: Model[] = [
  {
    id: 1,
    name: "gpt-4o-mini",
    displayName: "GPT-4o mini",
    description: "Compact version of GPT-4, ideal for quick tasks with limited resources.",
    modelType: ModelType.TEXT,
    labels: ["quick responses", "simple tasks"],
    isProModel: false,
    isLoginRequired: true,
    capabilities: ["vision", "agents"],
    categories: ["writing", "translation", "deep analysis"],
    tier: 1,
  },
  {
    id: 2,
    name: "gpt-4o",
    displayName: "GPT-4o",
    description: "Balanced GPT-4 model with strong versatility and moderate compute needs.",
    modelType: ModelType.TEXT,
    labels: ["writing", "translation", "deep analysis"],
    isProModel: true,
    isLoginRequired: true,
    capabilities: ["vision", "agents"],
    categories: ["writing", "translation", "deep analysis"],
    tier: 2,
  },
  {
    id: 3,
    name: "o1-preview",
    displayName: "o1 Preview",
    description: "A new series of reasoning models for solving hard problems.",
    modelType: ModelType.TEXT,
    labels: ["writing", "translation", "deep analysis"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["writing", "translation", "deep analysis"],
    tier: 3,
  },
  {
    id: 4,
    name: "o1-mini",
    displayName: "o1 Mini",
    description: "Lightweight and fast, perfect for low-resource or mobile environments.",
    modelType: ModelType.TEXT,
    labels: ["writing", "translation", "deep analysis"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["writing", "translation", "deep analysis"],
    tier: 3,
  },
  {
    id: 5,
    name: "perplexity",
    displayName: "Perplexity",
    description: "Specialized in dynamic knowledge retrieval and fact-based conversational AI.",
    modelType: ModelType.TEXT,
    labels: ["clear writing", "logical reasoning"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["writing", "translation", "deep analysis"],
    tier: 2,
  },
  {
    id: 7,
    name: "claude-3-haiku",
    displayName: "Claude 3 Haiku",
    description: "Optimized for creative, concise, and poetic text outputs.",
    modelType: ModelType.TEXT,
    labels: ["concise summaries", "brief responses"],
    isProModel: false,
    isLoginRequired: true,
    categories: ["writing", "translation", "deep analysis"],
    tier: 1,
  },
  {
    id: 25,
    name: "claude-3-5-haiku",
    displayName: "Claude 3.5 Haiku",
    description: "Optimized for creative, concise, and poetic text outputs.",
    modelType: ModelType.TEXT,
    labels: ["concise summaries", "brief responses"],
    isProModel: false,
    isLoginRequired: true,
    categories: ["writing", "translation", "deep analysis"],
    tier: 1,
  },
  {
    id: 48,
    name: "claude-4-sonnet",
    displayName: "Claude 4 Sonnet",
    description:
      "Claude 4 Sonnet combines advanced reasoning with creative capabilities, ideal for complex problem-solving and content creation.",
    modelType: ModelType.TEXT,
    labels: ["programming", "reasoning", "advanced analysis"],
    isProModel: true,
    isLoginRequired: true,
    capabilities: ["vision", "agents"],
    categories: ["writing", "translation", "deep analysis"],
    tier: 2,
  },
  {
    id: 49,
    name: "claude-4-opus",
    displayName: "Claude 4 Opus",
    description:
      "Claude 4 Opus delivers exceptional performance for the most demanding tasks, featuring superior reasoning and understanding capabilities.",
    modelType: ModelType.TEXT,
    labels: ["advanced reasoning", "complex tasks", "premium performance"],
    isProModel: true,
    isLoginRequired: true,
    capabilities: ["vision", "agents"],
    categories: ["writing", "translation", "deep analysis"],
    tier: 3,
  },

  // {
  //   id: 9,
  //   name: "llama-3.1-405b-reasoning",
  //   displayName: "Llama 3.1 405b",
  //   description:
  //     "Exceptional for complex reasoning and advanced problem-solving.",
  //   modelType: ModelType.MULTIMODAL,
  //   labels: ["programming", "balanced output"],
  //   isProModel: true,
  //   isLoginRequired: true,
  //   categories: ["writing", "translation", "deep analysis"],
  // },
  // {
  //   id: 11,
  //   name: "llama-3.1-8b-instant",
  //   displayName: "Llama 3.1 3b",
  //   description:
  //     "Fast and responsive, ideal for real-time interactive applications.",
  //   modelType: ModelType.TEXT,
  //   labels: ["programming", "balanced output"],
  //   isProModel: false,
  //   isLoginRequired: true,
  //   categories: ["writing", "translation", "deep analysis"],
  //   tier: 1,
  // },
  {
    id: 10,
    name: "llama-3.1-70b-versatile",
    displayName: "Llama 3.1 70b",
    description: "A versatile model excelling across various domains and tasks.",
    modelType: ModelType.TEXT,
    labels: ["programming", "balanced output"],
    isProModel: false,
    isLoginRequired: true,
    categories: ["writing", "translation", "deep analysis"],
    tier: 1,
  },
  // {
  //   id: 28,
  //   name: "llama-3.2-90b-vision-instruct",
  //   displayName: "Llama 3.2 90B",
  //   description:
  //     "Advanced multimodal model capable of understanding images and text, optimized for instruction following and visual reasoning tasks.",
  //   modelType: ModelType.TEXT,
  //   labels: ["programming", "balanced output"],
  //   isProModel: true,
  //   isLoginRequired: true,
  //   categories: [
  //     "visual analysis",
  //     "multimodal reasoning",
  //     "image understanding",
  //   ],
  //   tier: 2,
  // },
  // {
  //   id: 27,
  //   name: "llama-3.3-70b-instruct",
  //   displayName: "Llama 3.3 70b",
  //   description:
  //     "Latest Llama model optimized for instruction following and complex reasoning tasks.",
  //   modelType: ModelType.TEXT,
  //   labels: ["detailed images", "high-quality visuals"],
  //   isProModel: true,
  //   isLoginRequired: true,
  //   categories: ["writing", "translation", "deep analysis"],
  //   tier: 2,
  // },
  {
    id: 12,
    name: "sdxl-lightning-4step",
    displayName: "SDXL Lightning 4step",
    description: "Ultra-fast image generation with minimal steps for quick creativity.",
    modelType: ModelType.IMAGE,
    labels: ["quick image generation", "basic visuals"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["quick image generation", "basic visuals"],
  },
  // {
  //   id: 13,
  //   name: "stable-diffusion-3",
  //   displayName: "Stable Diffusion 3",
  //   description:
  //     "High-quality photorealistic image generation with strong flexibility.",
  //   modelType: ModelType.IMAGE,
  //   labels: ["artistic images", "creative design"],
  //   isProModel: true,
  //   isLoginRequired: true,
  //   categories: ["artistic images", "creative design"],
  // },
  {
    id: 14,
    name: "dall-e-3",
    displayName: "Dall-E 3",
    description: "Precise image generation with improved prompt adherence and inpainting.",
    modelType: ModelType.IMAGE,
    labels: ["detailed images", "high-quality visuals"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["detailed images", "high-quality visuals"],
  },
  // {
  //   id: 15,
  //   name: "flux-pro",
  //   displayName: "Flux Pro",
  //   description:
  //     "Generates high-quality, detailed images, but requires more computational power.",
  //   modelType: ModelType.IMAGE,
  //   labels: ["detailed images", "high-quality visuals"],
  //   isProModel: true,
  //   isLoginRequired: true,
  //   categories: ["detailed images", "high-quality visuals"],
  // },
  {
    id: 16,
    name: "sdxl-emoji",
    displayName: "SDXL Emoji",
    description: "Specialized model tailored for generating emoji-style images with high accuracy and variety.",
    modelType: ModelType.IMAGE,
    labels: ["detailed images", "high-quality visuals"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["detailed images", "high-quality visuals"],
  },
  {
    id: 17,
    name: "sdxl-barbie",
    displayName: "SDXL Barbie",
    description: "Specialized image generation model designed to create images in the iconic Barbie style.",
    modelType: ModelType.IMAGE,
    labels: ["detailed images", "high-quality visuals"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["detailed images", "high-quality visuals"],
  },
  {
    id: 18,
    name: "studio-ghibli",
    displayName: "Studio Ghibli",
    description: "Specialized model trained to replicate the distinctive art style of Studio Ghibli animations.",
    modelType: ModelType.IMAGE,
    labels: ["detailed images", "high-quality visuals"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["detailed images", "high-quality visuals"],
  },
  {
    id: 19,
    name: "gemini-1.5-flash",
    displayName: "Gemini 1.5 Flash",
    description: "Cost-effective model offering low latency and support for very long contexts.",
    modelType: ModelType.TEXT,
    labels: ["detailed images", "high-quality visuals"],
    isProModel: false,
    isLoginRequired: true,
    categories: ["detailed images", "high-quality visuals"],
    tier: 1,
  },
  {
    id: 20,
    name: "gemini-1.5-pro",
    displayName: "Gemini 1.5 Pro",
    description:
      "Advanced Gemini model with enhanced capabilities for complex tasks requiring deep understanding and generation.",
    modelType: ModelType.TEXT,
    labels: ["detailed images", "high-quality visuals"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["detailed images", "high-quality visuals"],
    tier: 2,
  },
  {
    id: 21,
    name: "animate-diff",
    displayName: "Animate Diff",
    description: "Generate a short and realistic video.",
    modelType: ModelType.VIDEO,
    labels: ["detailed images", "high-quality visuals"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["detailed images", "high-quality visuals"],
  },
  {
    id: 22,
    name: "hotshot-xl",
    displayName: "Hotshot XL",
    description: "Generate a impressive gif.",
    modelType: ModelType.VIDEO,
    labels: ["gifs"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["gifs"],
  },
  {
    id: 23,
    name: "nvidia/nemotron-70b-instruct",
    displayName: "NVIDIA Nemotron 70b",
    description: "High-performance instructional model optimized for precise task following and complex instructions",
    modelType: ModelType.TEXT,
    labels: ["detailed images", "high-quality visuals"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["detailed images", "high-quality visuals"],
    tier: 2,
  },
  // {
  //   id: 24,
  //   name: "grok-beta",
  //   displayName: "Grok Beta",
  //   description:
  //     "Experimental model excelling at real-time question answering and dynamic problem-solving.",
  //   modelType: ModelType.TEXT,
  //   labels: ["detailed images", "high-quality visuals"],
  //   isProModel: true,
  //   isLoginRequired: true,
  //   categories: ["detailed images", "high-quality visuals"],
  //   tier: 2,
  // },
  {
    id: 26,
    name: "animagine-xl-3.1",
    displayName: "Animagine XL 3.1",
    description: "Generate anime-based images.",
    modelType: ModelType.IMAGE,
    labels: ["detailed images", "high-quality visuals"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["detailed images", "high-quality visuals"],
  },
  {
    id: 27,
    name: "deepseek-v3",
    displayName: "DeepSeek V3",
    description: "Advanced language model optimized for coding, analysis and general text generation.",
    modelType: ModelType.TEXT,
    labels: ["coding", "analysis", "text generation"],
    isProModel: false,
    isLoginRequired: true,
    categories: ["coding", "analysis", "text generation"],
    tier: 1,
  },
  {
    id: 28,
    name: "flux-1.1-pro",
    displayName: "Flux 1.1 Pro",
    description: "Text-to-image model with excellent image quality, prompt adherence, and output diversity.",
    modelType: ModelType.IMAGE,
    labels: ["detailed images", "high-quality visuals"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["detailed images", "high-quality visuals"],
  },
  {
    id: 29,
    name: "stable-diffusion-3.5",
    displayName: "Stable Diffusion 3.5",
    description: "High-quality photorealistic image generation with fine details.",
    modelType: ModelType.IMAGE,
    labels: ["artistic images", "creative design"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["artistic images", "creative design"],
  },
  {
    id: 30,
    name: "grok-2",
    displayName: "Grok 2",
    description: "Enhanced model with improved accuracy, instruction adherence, and multilingual capabilities.",
    modelType: ModelType.TEXT,
    labels: ["detailed images", "high-quality visuals"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["detailed images", "high-quality visuals"],
    tier: 2,
  },
  {
    id: 31,
    name: "deepseek-r1",
    displayName: "DeepSeek R1",
    description:
      "Lastest reasoning model from DeepSeek, optimized for complex reasoning tasks such as coding and math.",
    modelType: ModelType.TEXT,
    labels: ["coding", "math"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["coding", "math"],
    tier: 2,
  },
  {
    id: 33,
    name: "grok-4",
    displayName: "Grok 4",
    description:
      "xAI's latest reasoning model with a 256k context window, multimodal capabilities, and advanced reasoning.",
    modelType: ModelType.TEXT,
    labels: ["reasoning", "multimodal", "large context"],
    isProModel: true,
    isLoginRequired: true,
    capabilities: ["vision", "agents"],
    categories: ["reasoning", "multimodal", "deep analysis"],
    tier: 3,
  },
  {
    id: 32,
    name: "o3-mini",
    displayName: "o3 Mini",
    description: "Fast and efficient reasoning model for complex tasks.",
    modelType: ModelType.TEXT,
    labels: ["coding", "math"],
    isProModel: true,
    isLoginRequired: true,
    categories: ["coding", "math"],
    tier: 2,
  },
  {
    id: 40,
    name: "o3-mini-high",
    displayName: "o3 Mini High",
    description: "Enhanced version of o3 Mini with improved performance for complex reasoning tasks.",
    modelType: ModelType.TEXT,
    labels: ["reasoning", "coding", "analysis"],
    categories: ["reasoning", "coding", "analysis"],
    isProModel: true,
    isLoginRequired: true,
    tier: 2,
  },
  {
    id: 41,
    name: "claude-3-7-sonnet",
    displayName: "Claude 3.7 Sonnet",
    description:
      "Anthropic's most advanced model with breakthrough performance in reasoning, coding, and multimodal understanding.",
    modelType: ModelType.TEXT,
    labels: ["reasoning", "coding", "multimodal", "analysis"],
    categories: ["reasoning", "coding", "multimodal", "analysis"],
    isProModel: true,
    isLoginRequired: true,
    tier: 2,
  },
  // {
  //   id: 42,
  //   name: "nvidia-llama-nemotron",
  //   displayName: "Llama Nemotron",
  //   description:
  //     "NVIDIA's enhanced Llama architecture optimized for multistep reasoning, coding, and complex decision-making tasks.",
  //   modelType: ModelType.TEXT,
  //   labels: ["reasoning", "coding", "decision-making"],
  //   categories: ["reasoning", "coding", "decision-making"],
  //   isProModel: true,
  //   isLoginRequired: true,
  //   tier: 2,
  // },
  {
    id: 43,
    name: "gemini-2.5-pro",
    displayName: "Gemini 2.5 Pro",
    description:
      "Google's robust reasoning model excelling in processing diverse data types and ranked highly in AI benchmarks like LMArena.",
    modelType: ModelType.TEXT,
    labels: ["reasoning", "multimodal", "benchmarking"],
    categories: ["reasoning", "multimodal", "benchmarking"],
    isProModel: true,
    isLoginRequired: true,
    tier: 2,
  },
  {
    id: 44,
    name: "gpt-4.1-nano",
    displayName: "GPT-4.1 Nano",
    description: "The fastest and most affordable model, optimized for low-latency, with a 1M token context window.​",
    modelType: ModelType.TEXT,
    labels: ["detailed images", "high-quality visuals"],
    categories: ["detailed images", "high-quality visuals"],
    isProModel: false,
    isLoginRequired: true,
    tier: 1,
  },
  {
    id: 45,
    name: "gpt-4.1-mini",
    displayName: "GPT-4.1 Mini",
    description:
      "Balanced performance and efficiency, matching or exceeding GPT-4o in many benchmarks, supporting a 1M token context window​",
    modelType: ModelType.TEXT,
    labels: ["detailed images", "high-quality visuals"],
    categories: ["detailed images", "high-quality visuals"],
    isProModel: true,
    isLoginRequired: true,
    tier: 2,
  },
  {
    id: 46,
    name: "gpt-4.1",
    displayName: "GPT-4.1",
    description:
      "Flagship model excelling in complex tasks, coding, and long-context processing, featuring a 1M token context window.​",
    modelType: ModelType.TEXT,
    labels: ["detailed images", "high-quality visuals"],
    categories: ["detailed images", "high-quality visuals"],
    isProModel: false,
    isLoginRequired: true,
    tier: 1,
  },
  {
    id: 47,
    name: "gemini-2.0-flash",
    displayName: "Gemini 2.0 Flash",
    description: "Google's latest generation of the Gemini model, optimized for fast and accurate text generation.",
    modelType: ModelType.TEXT,
    labels: ["fast text generation", "high-quality visuals"],
    categories: ["fast text generation", "high-quality visuals"],
    isProModel: false,
    isLoginRequired: false,
    tier: 1,
  },
  {
    id: 50,
    name: "o3",
    displayName: "o3",
    description:
      "OpenAI's most advanced reasoning model, excelling at complex mathematical, scientific, and coding tasks.",
    modelType: ModelType.TEXT,
    labels: ["reasoning", "coding", "math", "science"],
    categories: ["reasoning", "coding", "math", "science"],
    isProModel: true,
    isLoginRequired: true,
    tier: 3,
  },
  {
    id: 51,
    name: "gpt-4.5",
    displayName: "GPT-4.5",
    description:
      "Enhanced GPT-4 model with improved capabilities, better instruction following, and faster response times.",
    modelType: ModelType.TEXT,
    labels: ["writing", "translation", "deep analysis", "coding"],
    categories: ["writing", "translation", "deep analysis", "coding"],
    isProModel: true,
    isLoginRequired: true,
    tier: 2,
  },
  {
    id: 52,
    name: "gpt-5-nano",
    displayName: "GPT-5 Nano",
    description:
      "The most efficient GPT-5 model, optimized for speed and cost-effectiveness while maintaining high quality.",
    modelType: ModelType.TEXT,
    labels: ["quick responses", "efficient", "cost-effective"],
    categories: ["writing", "translation", "deep analysis"],
    isProModel: false,
    isLoginRequired: true,
    capabilities: ["vision", "agents"],
    tier: 1,
  },
  {
    id: 53,
    name: "gpt-5-mini",
    displayName: "GPT-5 Mini",
    description: "Compact GPT-5 model with excellent performance, balancing capability with efficiency.",
    modelType: ModelType.TEXT,
    labels: ["balanced performance", "versatile", "coding"],
    categories: ["writing", "translation", "deep analysis", "coding"],
    isProModel: true,
    isLoginRequired: true,
    capabilities: ["vision", "agents"],
    tier: 2,
  },
  {
    id: 54,
    name: "gpt-5",
    displayName: "GPT-5",
    description:
      "OpenAI's most advanced language model with breakthrough capabilities in reasoning, creativity, and complex problem-solving.",
    modelType: ModelType.TEXT,
    labels: ["advanced reasoning", "creative writing", "complex analysis", "coding"],
    categories: ["writing", "translation", "deep analysis", "coding", "reasoning"],
    isProModel: true,
    isLoginRequired: true,
    capabilities: ["vision", "agents"],
    tier: 2,
  },
  {
    id: 55,
    name: "claude-4.5-sonnet",
    displayName: "Claude 4.5 Sonnet",
    description:
      "Anthropic's enhanced Claude 4.5 Sonnet model with improved reasoning, coding, and multimodal understanding capabilities.",
    modelType: ModelType.TEXT,
    labels: ["programming", "reasoning", "advanced analysis", "multimodal"],
    isProModel: true,
    isLoginRequired: true,
    capabilities: ["vision", "agents"],
    categories: ["writing", "translation", "deep analysis", "coding"],
    tier: 2,
  },
];
