"use client";

import { MDX } from "@/components/mdx";
import clsx from "clsx";

const content = `# Terms of Service
Effective Date: Oct 17, 2024

Welcome to MentionAI. By accessing or using our service, you agree to be bound by the following terms and conditions. Please read them carefully. If you do not agree, please refrain from using our service.

### 1. Overview of Service
MentionAI provides access to advanced AI models for text and image generation. Users interact with the AI by using the "@" mention system. All conversations and images are processed by AI models provided by MentionAI.

### 2. User Accounts and Login
Users can log in only via third-party social network accounts (e.g., Google or GitHub).
By using MentionAI, you agree to comply with the policies and terms of service of the social network providers you use to log in.
### 3. Usage Guidelines
You are responsible for the content generated during interactions with MentionAI.
You agree not to misuse the platform for illegal activities or to generate content that is abusive, obscene, or violates the rights of others.
MentionAI reserves the right to suspend or terminate access for any behavior that violates these terms.

### 4. Data Storage
Conversations with AI models will be stored in our database, except when anonymous mode is enabled. In anonymous mode, no data will be stored.
Generated images will be stored on Amazon S3 for retrieval and future access.

### 5. Ownership and Intellectual Property
Content generated by MentionAI may involve both AI models and user input. While you retain rights over your input, MentionAI may retain certain rights to the generated content for platform development and improvement.
MentionAI is not responsible for any copyright or intellectual property issues arising from the use or misuse of generated content.
### 6. Service Changes and Availability
MentionAI reserves the right to modify, update, or discontinue the service at any time without prior notice.
We do not guarantee uninterrupted access to the service.
### 7. Limitation of Liability
MentionAI is provided "as is" without any warranties, express or implied.
MentionAI will not be liable for any indirect, incidental, or consequential damages resulting from the use or inability to use the service.
### 8. Changes to the Terms of Service
MentionAI may revise these terms at any time. Continued use of the service after changes take effect constitutes acceptance of the new terms.
### 9. Contact
For questions or concerns, please contact us at: contact@mentionai.io`;

export default function TermsOfServicePage() {
  return (
    <div
      className={clsx(
        "flex flex-col items-center justify-center prose prose-markdown prose-p:text-[15px] prose-p:leading-6 w-full max-w-3xl mx-auto py-6 md:py-8 lg:py-10 px-4 md:px-6",
        {
          "prose-h1:text-2xl prose-h1:font-semibold": true,
          "prose-h2:text-xl prose-h2:font-semibold": true,
          "prose-h3:text-base prose-h3:font-semibold": true,
          "prose-h4:text-sm prose-h2:font-medium": true,
        }
      )}
    >
      <MDX animate={false} messageId="privacy">
        {content}
      </MDX>
    </div>
  );
}
