"use client";

import { MDX } from "@/components/mdx";
import clsx from "clsx";

const content = `# Privacy Policy
Effective Date: June 6, 2025

Your privacy is important to us. This policy outlines how MentionAI collects, stores, and handles user data.

## 1. Data We Collect
**Login Data**: We collect information from the social network providers (Google, GitHub, Facebook) used for login, including basic profile details such as name, email address, and profile picture.

**Conversation Data**: Interactions with the AI are stored in our database unless anonymous mode is enabled, in which case no data is saved.

**Generated Images**: Images generated by the AI are stored on Amazon S3.

**Social Media Content**: When you connect your social media accounts (Facebook, Twitter, Instagram, etc.), we may collect and process posts, messages, and other content you choose to share for building your personal AI assistant.

**Uploaded Files**: Files you upload to build your personal AI assistant are processed and may be stored securely on our servers and cloud storage services.

**Personal AI Training Data**: Information and content you provide specifically for training your personal AI assistant, including but not limited to documents, preferences, and custom instructions.

## 2. How We Use Your Data
- Improve AI models and service performance
- Personalize user experience and build custom AI assistants
- Store generated images for easy access
- Process social media content and uploaded files to create personalized AI responses
- Ensure service security and prevent misuse
- Comply with legal obligations and platform requirements

## 3. Anonymous Mode
When anonymous mode is enabled, conversations and interactions will not be saved.
Generated images will still be stored on Amazon S3 unless explicitly deleted by the user.
Personal AI features and social media connections are not available in anonymous mode.

## 4. Third-Party Services
We use social network providers (Google, GitHub, Facebook) for authentication. By logging in via these providers, you agree to their privacy policies.

When you connect social media accounts, we access only the data necessary to provide our services and in accordance with the permissions you grant.

Amazon S3 and other cloud services are used for data storage. Your data may be processed in accordance with their respective terms and policies.

## 5. Data Sharing
We do not share your personal data with third parties, except:
- As required by law or legal process
- For security purposes to prevent fraud or abuse
- With your explicit consent
- With service providers who assist in delivering our services (under strict confidentiality agreements)

## 6. Data Security
We implement appropriate technical and organizational measures to protect data from unauthorized access, alteration, disclosure, or destruction.
Users are responsible for safeguarding access to their MentionAI account via the social network accounts used for login.
All data transmissions are encrypted using industry-standard protocols.

## 7. Data Retention and Deletion
**General Data**: Conversation data will be stored unless anonymous mode is enabled. Users can request deletion of their stored interactions.

**Generated Images**: Retained on Amazon S3 until explicitly deleted by the user or upon account deletion.

**Social Media Data**: Data from connected social media accounts is retained only as long as necessary to provide personalized AI services or until you disconnect the account.

**Personal AI Data**: Training data and uploaded files are retained to maintain your personal AI assistant's functionality until you request deletion.

**Data Deletion Requests**: In compliance with platform policies including Facebook's data deletion requirements, you have the right to request deletion of your data. To request data deletion:

1. **Email Request**: Send a data deletion request to contact@mentionai.io with the subject line "Data Deletion Request"
2. **Include Information**: Provide your account email and specify which data you want deleted
3. **Confirmation Process**: We will respond within 30 days with a confirmation number and status update
4. **Status Tracking**: You can check the status of your deletion request by contacting us with your confirmation number

We will delete your data within 90 days of your request, except where retention is required by law. For Facebook-connected accounts, we comply with Facebook's data deletion callback requirements and will process deletion requests accordingly.

## 8. Your Rights
You have the right to:
- Access your personal data
- Correct inaccurate data
- Request deletion of your data
- Object to processing of your data
- Data portability (receive a copy of your data)
- Withdraw consent for data processing

## 9. Children's Privacy
MentionAI is not intended for children under 13. We do not knowingly collect data from children.

## 10. International Data Transfers
Your data may be transferred to and processed in countries other than your own. We ensure appropriate safeguards are in place for such transfers.

## 11. Changes to the Privacy Policy
We may update this policy periodically. Continued use of MentionAI after policy changes constitutes acceptance of the new terms. We will notify users of significant changes via email or platform notification.

## 12. Contact Us
For questions, concerns, or data deletion requests regarding this policy, please contact us at:

**Email**: contact@mentionai.io
**Subject Line for Deletion Requests**: "Data Deletion Request"

We are committed to addressing your privacy concerns promptly and transparently.`;

export default function PrivacyPage() {
  return (
    <div
      className={clsx(
        "flex flex-col items-center justify-center prose prose-markdown prose-p:text-[15px] prose-p:leading-6 w-full max-w-3xl mx-auto py-6 md:py-8 lg:py-10 px-4 md:px-6",
        {
          "prose-h1:text-2xl prose-h1:font-semibold": true,
          "prose-h2:text-xl prose-h2:font-semibold": true,
          "prose-h3:text-base prose-h3:font-semibold": true,
          "prose-h4:text-sm prose-h2:font-medium": true,
        }
      )}
    >
      <MDX animate={false} messageId="terms-of-service">
        {content}
      </MDX>
    </div>
  );
}
