import { Model } from "@/services/api";

export const BACKEND_URL =
  process.env.NEXT_PUBLIC_BACKEND_URL || process.env.BACKEND_URL;

export enum ModelType {
  TEXT = "text",
  IMAGE = "image",
  VIDEO = "video",
}

// Suggested questions character limit
export const SUGGESTED_QUESTION_MAX_LENGTH = 200;
// Maximum number of suggested questions
export const SUGGESTED_QUESTION_MAX_COUNT = 6;

export const AVAILABLE_MODELS: Model[] = [
  {
    id: 1,
    name: "gpt-4o-mini",
    displayName: "GPT-4o mini",
    description:
      "Compact version of GPT-4, ideal for quick tasks with limited resources.",
    modelType: ModelType.TEXT,
    isProModel: false,
    isLoginRequired: true,
    tier: 1,
    isReasoning: false,
    supportsImageInput: true,
    supportsWebSearch: true,
  },
  // {
  //   id: 2,
  //   name: "gpt-4o",
  //   displayName: "GPT-4o",
  //   description:
  //     "Balanced GPT-4 model with strong versatility and moderate compute needs.",
  //   modelType: ModelType.TEXT,
  //   isProModel: true,
  //   isLoginRequired: true,
  //   tier: 2,
  //   isReasoning: false,
  //   supportsImageInput: true,
  //   supportsWebSearch: true,
  // },
  // {
  //   id: 3,
  //   name: "o1-preview",
  //   displayName: "o1 Preview",
  //   description: "A new series of reasoning models for solving hard problems.",
  //   modelType: ModelType.TEXT,
  //   isProModel: true,
  //   isLoginRequired: true,
  //   tier: 3,
  // },
  // {
  //   id: 44,
  //   name: "gpt-4.1-nano",
  //   displayName: "GPT-4.1 Nano",
  //   description:
  //     "The fastest and most affordable model, optimized for low-latency, with a 1M token context window.​",
  //   modelType: ModelType.TEXT,
  //   isProModel: false,
  //   isLoginRequired: true,
  //   tier: 1,
  //   isReasoning: false,
  //   supportsImageInput: true,
  //   supportsWebSearch: true,
  // },
  // {
  //   id: 45,
  //   name: "gpt-4.1-mini",
  //   displayName: "GPT-4.1 Mini",
  //   description:
  //     "Balanced performance and efficiency, matching or exceeding GPT-4o in many benchmarks, supporting a 1M token context window​",
  //   modelType: ModelType.TEXT,
  //   isProModel: true,
  //   isLoginRequired: true,
  //   tier: 2,
  //   isReasoning: false,
  //   supportsImageInput: true,
  //   supportsWebSearch: true,
  // },
  {
    id: 46,
    name: "gpt-4.1",
    displayName: "GPT-4.1",
    description:
      "Flagship model excelling in complex tasks, coding, and long-context processing, featuring a 1M token context window.​",
    modelType: ModelType.TEXT,
    isProModel: false,
    isLoginRequired: true,
    tier: 1,
    isReasoning: true,
    supportsImageInput: true,
    supportsWebSearch: true,
  },
  // {
  //   id: 52,
  //   name: "gpt-5-nano",
  //   displayName: "GPT-5 Nano",
  //   description:
  //     "The most efficient GPT-5 model, optimized for speed and cost-effectiveness while maintaining high quality.",
  //   modelType: ModelType.TEXT,
  //   isProModel: false,
  //   isLoginRequired: true,
  //   tier: 1,
  //   isReasoning: false,
  //   supportsImageInput: true,
  //   supportsWebSearch: true,
  // },
  {
    id: 53,
    name: "gpt-5-mini",
    displayName: "GPT-5 Mini",
    description:
      "Compact GPT-5 model with excellent performance, balancing capability with efficiency.",
    modelType: ModelType.TEXT,
    isProModel: true,
    isLoginRequired: true,
    tier: 2,
    isReasoning: false,
    supportsImageInput: true,
    supportsWebSearch: true,
  },
  {
    id: 54,
    name: "gpt-5",
    displayName: "GPT-5",
    description:
      "OpenAI's most advanced language model with breakthrough capabilities in reasoning, creativity, and complex problem-solving.",
    modelType: ModelType.TEXT,
    isProModel: true,
    isLoginRequired: true,
    tier: 3,
    isReasoning: true,
    supportsImageInput: true,
    supportsWebSearch: true,
  },
  // {
  //   id: 32,
  //   name: "o3-mini",
  //   displayName: "o3 Mini",
  //   description: "Fast and efficient reasoning model for complex tasks.",
  //   modelType: ModelType.TEXT,
  //   isProModel: true,
  //   isLoginRequired: true,
  //   tier: 2,
  //   isReasoning: true,
  //   supportsImageInput: false,
  //   supportsWebSearch: false,
  // },
  // {
  //   id: 40,
  //   name: "o3-mini-high",
  //   displayName: "o3 Mini High",
  //   description:
  //     "Enhanced version of o3 Mini with improved performance for complex reasoning tasks.",
  //   modelType: ModelType.TEXT,
  //   isProModel: true,
  //   isLoginRequired: true,
  //   tier: 2,
  //   isReasoning: true,
  //   supportsImageInput: false,
  //   supportsWebSearch: false,
  // },
  {
    id: 5,
    name: "perplexity",
    displayName: "Perplexity",
    description:
      "Specialized in dynamic knowledge retrieval and fact-based conversational AI.",
    modelType: ModelType.TEXT,
    isProModel: true,
    isLoginRequired: true,
    tier: 2,
    isReasoning: false,
    supportsImageInput: false,
    supportsWebSearch: true,
  },
  // {
  //   id: 7,
  //   name: "claude-3-haiku",
  //   displayName: "Claude 3 Haiku",
  //   description: "Optimized for creative, concise, and poetic text outputs.",
  //   modelType: ModelType.TEXT,
  //   isProModel: false,
  //   isLoginRequired: true,
  //   tier: 1,
  //   isReasoning: false,
  //   supportsImageInput: true,
  //   supportsWebSearch: true,
  // },
  // {
  //   id: 25,
  //   name: "claude-3-5-haiku",
  //   displayName: "Claude 3.5 Haiku",
  //   description: "Optimized for creative, concise, and poetic text outputs.",
  //   modelType: ModelType.TEXT,
  //   isProModel: false,
  //   isLoginRequired: true,
  //   tier: 1,
  //   isReasoning: false,
  //   supportsImageInput: true,
  //   supportsWebSearch: true,
  // },
  // {
  //   id: 48,
  //   name: "claude-4-sonnet",
  //   displayName: "Claude 4 Sonnet",
  //   description:
  //     "Claude 4 Sonnet combines advanced reasoning with creative capabilities, ideal for complex problem-solving and content creation.",
  //   modelType: ModelType.TEXT,
  //   isProModel: true,
  //   isLoginRequired: true,
  //   tier: 2,
  //   isReasoning: true,
  //   supportsImageInput: true,
  //   supportsWebSearch: true,
  // },
  {
    id: 49,
    name: "claude-4-opus",
    displayName: "Claude 4 Opus",
    description:
      "Claude 4 Opus delivers exceptional performance for the most demanding tasks, featuring superior reasoning and understanding capabilities.",
    modelType: ModelType.TEXT,
    isProModel: true,
    isLoginRequired: true,
    tier: 3,
    isReasoning: true,
    supportsImageInput: true,
    supportsWebSearch: true,
  },
  {
    id: 55,
    name: "claude-4.5-sonnet",
    displayName: "Claude 4.5 Sonnet",
    description:
      "Anthropic's enhanced Claude 4.5 Sonnet model with improved reasoning, coding, and multimodal understanding capabilities.",
    modelType: ModelType.TEXT,
    isProModel: true,
    isLoginRequired: true,
    tier: 2,
    isReasoning: true,
    supportsImageInput: true,
    supportsWebSearch: true,
  },
  // {
  //   id: 41,
  //   name: "claude-3-7-sonnet",
  //   displayName: "Claude 3.7 Sonnet",
  //   description:
  //     "Anthropic's most advanced model with breakthrough performance in reasoning, coding, and multimodal understanding.",
  //   modelType: ModelType.TEXT,
  //   isProModel: true,
  //   isLoginRequired: true,
  //   tier: 3,
  //   isReasoning: true,
  //   supportsImageInput: true,
  //   supportsWebSearch: true,
  // },
  {
    id: 27,
    name: "deepseek-v3",
    displayName: "DeepSeek V3",
    description:
      "Advanced language model optimized for coding, analysis and general text generation.",
    modelType: ModelType.TEXT,
    isProModel: false,
    isLoginRequired: true,
    tier: 1,
    isReasoning: false,
    supportsImageInput: true,
    supportsWebSearch: true,
  },

  {
    id: 31,
    name: "deepseek-r1",
    displayName: "DeepSeek R1",
    description:
      "Lastest reasoning model from DeepSeek, optimized for complex reasoning tasks such as coding and math.",
    modelType: ModelType.TEXT,
    isProModel: true,
    isLoginRequired: true,
    tier: 2,
    isReasoning: true,
    supportsImageInput: true,
    supportsWebSearch: true,
  },
  {
    id: 10,
    name: "llama-3.1-70b-versatile",
    displayName: "Llama 3.1 70b",
    description:
      "A versatile model excelling across various domains and tasks.",
    modelType: ModelType.TEXT,
    isProModel: false,
    isLoginRequired: true,
    tier: 1,
    isReasoning: false,
    supportsImageInput: true,
    supportsWebSearch: true,
  },
  {
    id: 12,
    name: "sdxl-lightning-4step",
    displayName: "SDXL Lightning 4step",
    description:
      "Ultra-fast image generation with minimal steps for quick creativity.",
    modelType: ModelType.IMAGE,
    isProModel: true,
    isLoginRequired: true,
  },

  {
    id: 14,
    name: "dall-e-3",
    displayName: "Dall-E 3",
    description:
      "Precise image generation with improved prompt adherence and inpainting.",
    modelType: ModelType.IMAGE,
    isProModel: true,
    isLoginRequired: true,
  },

  {
    id: 16,
    name: "sdxl-emoji",
    displayName: "SDXL Emoji",
    description:
      "Specialized model tailored for generating emoji-style images with high accuracy and variety.",
    modelType: ModelType.IMAGE,
    isProModel: true,
    isLoginRequired: true,
  },
  {
    id: 17,
    name: "sdxl-barbie",
    displayName: "SDXL Barbie",
    description:
      "Specialized image generation model designed to create images in the iconic Barbie style.",
    modelType: ModelType.IMAGE,
    isProModel: true,
    isLoginRequired: true,
  },
  {
    id: 18,
    name: "studio-ghibli",
    displayName: "Studio Ghibli",
    description:
      "Specialized model trained to replicate the distinctive art style of Studio Ghibli animations.",
    modelType: ModelType.IMAGE,
    isProModel: true,
    isLoginRequired: true,
  },
  // {
  //   id: 19,
  //   name: "gemini-1.5-flash",
  //   displayName: "Gemini 1.5 Flash",
  //   description:
  //     "Cost-effective model offering low latency and support for very long contexts.",
  //   modelType: ModelType.TEXT,
  //   isProModel: false,
  //   isLoginRequired: true,
  //   tier: 1,
  // },
  {
    id: 47,
    name: "gemini-2.0-flash",
    displayName: "Gemini 2.0 Flash",
    description:
      "Google's latest generation of the Gemini model, optimized for fast and accurate text generation.",
    modelType: ModelType.TEXT,
    isProModel: false,
    isLoginRequired: false,
    tier: 1,
    isReasoning: false,
    supportsImageInput: true,
    supportsWebSearch: true,
  },
  // {
  //   id: 20,
  //   name: "gemini-1.5-pro",
  //   displayName: "Gemini 1.5 Pro",
  //   description:
  //     "Advanced Gemini model with enhanced capabilities for complex tasks requiring deep understanding and generation.",
  //   modelType: ModelType.TEXT,
  //   isProModel: true,
  //   isLoginRequired: true,
  //   tier: 2,
  // },
  {
    id: 43,
    name: "gemini-2.5-pro",
    displayName: "Gemini 2.5 Pro",
    description:
      "Google's robust reasoning model excelling in processing diverse data types and ranked highly in AI benchmarks like LMArena.",
    modelType: ModelType.TEXT,
    isProModel: true,
    isLoginRequired: true,
    tier: 2,
    isReasoning: true,
    supportsImageInput: true,
    supportsWebSearch: true,
  },
  {
    id: 21,
    name: "animate-diff",
    displayName: "Animate Diff",
    description: "Generate a short and realistic video.",
    modelType: ModelType.VIDEO,
    isProModel: true,
    isLoginRequired: true,
  },
  {
    id: 22,
    name: "hotshot-xl",
    displayName: "Hotshot XL",
    description: "Generate a impressive gif.",
    modelType: ModelType.VIDEO,
    isProModel: true,
    isLoginRequired: true,
  },
  // {
  //   id: 23,
  //   name: "nvidia/nemotron-70b-instruct",
  //   displayName: "NVIDIA Nemotron 70b",
  //   description:
  //     "High-performance instructional model optimized for precise task following and complex instructions",
  //   modelType: ModelType.TEXT,
  //   isProModel: true,
  //   isLoginRequired: true,
  //   tier: 2,
  // },

  {
    id: 26,
    name: "animagine-xl-3.1",
    displayName: "Animagine XL 3.1",
    description: "Generate anime-based images.",
    modelType: ModelType.IMAGE,
    isProModel: true,
    isLoginRequired: true,
  },

  {
    id: 28,
    name: "flux-1.1-pro",
    displayName: "Flux 1.1 Pro",
    description:
      "Text-to-image model with excellent image quality, prompt adherence, and output diversity.",
    modelType: ModelType.IMAGE,
    isProModel: true,
    isLoginRequired: true,
  },
  {
    id: 29,
    name: "stable-diffusion-3.5",
    displayName: "Stable Diffusion 3.5",
    description:
      "High-quality photorealistic image generation with fine details.",
    modelType: ModelType.IMAGE,
    isProModel: true,
    isLoginRequired: true,
  },

  // {
  //   id: 30,
  //   name: "grok-2",
  //   displayName: "Grok 2",
  //   description:
  //     "Enhanced model with improved accuracy, instruction adherence, and multilingual capabilities.",
  //   modelType: ModelType.TEXT,
  //   isProModel: true,
  //   isLoginRequired: true,
  //   tier: 2,
  //   isReasoning: false,
  //   supportsImageInput: true,
  //   supportsWebSearch: true,
  // },

  {
    id: 33,
    name: "grok-4",
    displayName: "Grok 4",
    description:
      "xAI's latest reasoning model with a 256k context window, multimodal capabilities, and advanced reasoning.",
    modelType: ModelType.TEXT,
    isProModel: true,
    isLoginRequired: true,
    tier: 3,
    isReasoning: true,
    supportsImageInput: true,
    supportsWebSearch: true,
  },

  // {
  //   id: 42,
  //   name: "nvidia-llama-nemotron",
  //   displayName: "Llama Nemotron",
  //   description:
  //     "NVIDIA's enhanced Llama architecture optimized for multistep reasoning, coding, and complex decision-making tasks.",
  //   modelType: ModelType.TEXT,
  //   isProModel: true,
  //   isLoginRequired: true,
  //   tier: 2,
  // },

  // {
  //   id: 51,
  //   name: "gpt-4.5",
  //   displayName: "GPT-4.5",
  //   description:
  //     "Enhanced GPT-4 model with improved capabilities, better instruction following, and faster response times.",
  //   modelType: ModelType.TEXT,
  //   isProModel: true,
  //   isLoginRequired: true,
  //   tier: 2,
  //   isReasoning: false,
  //   supportsImageInput: true,
  //   supportsWebSearch: true,
  // },
];
